/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.pharmatrace.api.scin.public.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Pharmaceutical {
  
  @SerializedName("pharmaceutical_id")
  private String pharmaceuticalId = null;
  @SerializedName("gtin")
  private String gtin = null;
  @SerializedName("trade_name")
  private String tradeName = null;
  @SerializedName("ean_code")
  private String eanCode = null;
  @SerializedName("manufacturer_id")
  private String manufacturerId = null;
  @SerializedName("image")
  private String image = null;

  /**
   * Either gtin or synthetical for precision medicine.
   **/
  @ApiModelProperty(value = "Either gtin or synthetical for precision medicine.")
  public String getPharmaceuticalId() {
    return pharmaceuticalId;
  }
  public void setPharmaceuticalId(String pharmaceuticalId) {
    this.pharmaceuticalId = pharmaceuticalId;
  }

  /**
   * Global trade item number (GS1)
   **/
  @ApiModelProperty(value = "Global trade item number (GS1)")
  public String getGtin() {
    return gtin;
  }
  public void setGtin(String gtin) {
    this.gtin = gtin;
  }

  /**
   * Manufacturers official name of the pharmaceutical product.
   **/
  @ApiModelProperty(value = "Manufacturers official name of the pharmaceutical product.")
  public String getTradeName() {
    return tradeName;
  }
  public void setTradeName(String tradeName) {
    this.tradeName = tradeName;
  }

  /**
   * EAN code.
   **/
  @ApiModelProperty(value = "EAN code.")
  public String getEanCode() {
    return eanCode;
  }
  public void setEanCode(String eanCode) {
    this.eanCode = eanCode;
  }

  /**
   * Manufaturer id
   **/
  @ApiModelProperty(value = "Manufaturer id")
  public String getManufacturerId() {
    return manufacturerId;
  }
  public void setManufacturerId(String manufacturerId) {
    this.manufacturerId = manufacturerId;
  }

  /**
   * Image URL representing the product.
   **/
  @ApiModelProperty(value = "Image URL representing the product.")
  public String getImage() {
    return image;
  }
  public void setImage(String image) {
    this.image = image;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pharmaceutical pharmaceutical = (Pharmaceutical) o;
    return (this.pharmaceuticalId == null ? pharmaceutical.pharmaceuticalId == null : this.pharmaceuticalId.equals(pharmaceutical.pharmaceuticalId)) &&
        (this.gtin == null ? pharmaceutical.gtin == null : this.gtin.equals(pharmaceutical.gtin)) &&
        (this.tradeName == null ? pharmaceutical.tradeName == null : this.tradeName.equals(pharmaceutical.tradeName)) &&
        (this.eanCode == null ? pharmaceutical.eanCode == null : this.eanCode.equals(pharmaceutical.eanCode)) &&
        (this.manufacturerId == null ? pharmaceutical.manufacturerId == null : this.manufacturerId.equals(pharmaceutical.manufacturerId)) &&
        (this.image == null ? pharmaceutical.image == null : this.image.equals(pharmaceutical.image));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.pharmaceuticalId == null ? 0: this.pharmaceuticalId.hashCode());
    result = 31 * result + (this.gtin == null ? 0: this.gtin.hashCode());
    result = 31 * result + (this.tradeName == null ? 0: this.tradeName.hashCode());
    result = 31 * result + (this.eanCode == null ? 0: this.eanCode.hashCode());
    result = 31 * result + (this.manufacturerId == null ? 0: this.manufacturerId.hashCode());
    result = 31 * result + (this.image == null ? 0: this.image.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pharmaceutical {\n");
    
    sb.append("  pharmaceuticalId: ").append(pharmaceuticalId).append("\n");
    sb.append("  gtin: ").append(gtin).append("\n");
    sb.append("  tradeName: ").append(tradeName).append("\n");
    sb.append("  eanCode: ").append(eanCode).append("\n");
    sb.append("  manufacturerId: ").append(manufacturerId).append("\n");
    sb.append("  image: ").append(image).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
