/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Container {
  
  @SerializedName("container_id")
  private String containerId = null;
  @SerializedName("epc_code")
  private String epcCode = null;
  @SerializedName("label")
  private String label = null;
  @SerializedName("barcode")
  private String barcode = null;
  @SerializedName("rf_id")
  private String rfId = null;
  @SerializedName("quantity")
  private BigDecimal quantity = null;
  @SerializedName("unit")
  private String unit = null;
  @SerializedName("current_location_id")
  private String currentLocationId = null;
  @SerializedName("owner_stakeholder_id")
  private String ownerStakeholderId = null;
  @SerializedName("parent_container_id")
  private String parentContainerId = null;

  /**
   * Unique identifier representing a specific container.
   **/
  @ApiModelProperty(value = "Unique identifier representing a specific container.")
  public String getContainerId() {
    return containerId;
  }
  public void setContainerId(String containerId) {
    this.containerId = containerId;
  }

  /**
   * EPC code
   **/
  @ApiModelProperty(value = "EPC code")
  public String getEpcCode() {
    return epcCode;
  }
  public void setEpcCode(String epcCode) {
    this.epcCode = epcCode;
  }

  /**
   * Serialization label.
   **/
  @ApiModelProperty(value = "Serialization label.")
  public String getLabel() {
    return label;
  }
  public void setLabel(String label) {
    this.label = label;
  }

  /**
   * barcode on container. Normally equal to container id.
   **/
  @ApiModelProperty(value = "barcode on container. Normally equal to container id.")
  public String getBarcode() {
    return barcode;
  }
  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  /**
   * RFID of RF tracking label on conatiner.
   **/
  @ApiModelProperty(value = "RFID of RF tracking label on conatiner.")
  public String getRfId() {
    return rfId;
  }
  public void setRfId(String rfId) {
    this.rfId = rfId;
  }

  /**
   * quantity of product in container.
   **/
  @ApiModelProperty(value = "quantity of product in container.")
  public BigDecimal getQuantity() {
    return quantity;
  }
  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  /**
   * Unit for quantity measurement.
   **/
  @ApiModelProperty(value = "Unit for quantity measurement.")
  public String getUnit() {
    return unit;
  }
  public void setUnit(String unit) {
    this.unit = unit;
  }

  /**
   * Location id of last tracked locaction.
   **/
  @ApiModelProperty(value = "Location id of last tracked locaction.")
  public String getCurrentLocationId() {
    return currentLocationId;
  }
  public void setCurrentLocationId(String currentLocationId) {
    this.currentLocationId = currentLocationId;
  }

  /**
   * stakeholder id of the last tracked owner of the container.
   **/
  @ApiModelProperty(value = "stakeholder id of the last tracked owner of the container.")
  public String getOwnerStakeholderId() {
    return ownerStakeholderId;
  }
  public void setOwnerStakeholderId(String ownerStakeholderId) {
    this.ownerStakeholderId = ownerStakeholderId;
  }

  /**
   * id of the parent container or null.
   **/
  @ApiModelProperty(value = "id of the parent container or null.")
  public String getParentContainerId() {
    return parentContainerId;
  }
  public void setParentContainerId(String parentContainerId) {
    this.parentContainerId = parentContainerId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Container container = (Container) o;
    return (this.containerId == null ? container.containerId == null : this.containerId.equals(container.containerId)) &&
        (this.epcCode == null ? container.epcCode == null : this.epcCode.equals(container.epcCode)) &&
        (this.label == null ? container.label == null : this.label.equals(container.label)) &&
        (this.barcode == null ? container.barcode == null : this.barcode.equals(container.barcode)) &&
        (this.rfId == null ? container.rfId == null : this.rfId.equals(container.rfId)) &&
        (this.quantity == null ? container.quantity == null : this.quantity.equals(container.quantity)) &&
        (this.unit == null ? container.unit == null : this.unit.equals(container.unit)) &&
        (this.currentLocationId == null ? container.currentLocationId == null : this.currentLocationId.equals(container.currentLocationId)) &&
        (this.ownerStakeholderId == null ? container.ownerStakeholderId == null : this.ownerStakeholderId.equals(container.ownerStakeholderId)) &&
        (this.parentContainerId == null ? container.parentContainerId == null : this.parentContainerId.equals(container.parentContainerId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.containerId == null ? 0: this.containerId.hashCode());
    result = 31 * result + (this.epcCode == null ? 0: this.epcCode.hashCode());
    result = 31 * result + (this.label == null ? 0: this.label.hashCode());
    result = 31 * result + (this.barcode == null ? 0: this.barcode.hashCode());
    result = 31 * result + (this.rfId == null ? 0: this.rfId.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    result = 31 * result + (this.unit == null ? 0: this.unit.hashCode());
    result = 31 * result + (this.currentLocationId == null ? 0: this.currentLocationId.hashCode());
    result = 31 * result + (this.ownerStakeholderId == null ? 0: this.ownerStakeholderId.hashCode());
    result = 31 * result + (this.parentContainerId == null ? 0: this.parentContainerId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Container {\n");
    
    sb.append("  containerId: ").append(containerId).append("\n");
    sb.append("  epcCode: ").append(epcCode).append("\n");
    sb.append("  label: ").append(label).append("\n");
    sb.append("  barcode: ").append(barcode).append("\n");
    sb.append("  rfId: ").append(rfId).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("  unit: ").append(unit).append("\n");
    sb.append("  currentLocationId: ").append(currentLocationId).append("\n");
    sb.append("  ownerStakeholderId: ").append(ownerStakeholderId).append("\n");
    sb.append("  parentContainerId: ").append(parentContainerId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
