/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Profile {
  
  @SerializedName("first_name")
  private String firstName = null;
  @SerializedName("last_name")
  private String lastName = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("twitter_name")
  private String twitterName = null;
  @SerializedName("linkedin_name")
  private String linkedinName = null;
  @SerializedName("facebook_name")
  private String facebookName = null;
  @SerializedName("picture")
  private String picture = null;
  @SerializedName("stakeholder_id")
  private String stakeholderId = null;
  @SerializedName("active")
  private Boolean active = null;

  /**
   * First name of the PT network user.
   **/
  @ApiModelProperty(value = "First name of the PT network user.")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   * Last name of the PT network user.
   **/
  @ApiModelProperty(value = "Last name of the PT network user.")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   * Email address
   **/
  @ApiModelProperty(value = "Email address")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * Twitter name
   **/
  @ApiModelProperty(value = "Twitter name")
  public String getTwitterName() {
    return twitterName;
  }
  public void setTwitterName(String twitterName) {
    this.twitterName = twitterName;
  }

  /**
   * LinkedIn name
   **/
  @ApiModelProperty(value = "LinkedIn name")
  public String getLinkedinName() {
    return linkedinName;
  }
  public void setLinkedinName(String linkedinName) {
    this.linkedinName = linkedinName;
  }

  /**
   * Facebook name
   **/
  @ApiModelProperty(value = "Facebook name")
  public String getFacebookName() {
    return facebookName;
  }
  public void setFacebookName(String facebookName) {
    this.facebookName = facebookName;
  }

  /**
   * Image URL
   **/
  @ApiModelProperty(value = "Image URL")
  public String getPicture() {
    return picture;
  }
  public void setPicture(String picture) {
    this.picture = picture;
  }

  /**
   * the PT network member that the user/profile is assigned to.
   **/
  @ApiModelProperty(value = "the PT network member that the user/profile is assigned to.")
  public String getStakeholderId() {
    return stakeholderId;
  }
  public void setStakeholderId(String stakeholderId) {
    this.stakeholderId = stakeholderId;
  }

  /**
   * true if the user is currently active. Inactive users will be anonymized but not deleted to maintain integrity of transaction history
   **/
  @ApiModelProperty(value = "true if the user is currently active. Inactive users will be anonymized but not deleted to maintain integrity of transaction history")
  public Boolean getActive() {
    return active;
  }
  public void setActive(Boolean active) {
    this.active = active;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Profile profile = (Profile) o;
    return (this.firstName == null ? profile.firstName == null : this.firstName.equals(profile.firstName)) &&
        (this.lastName == null ? profile.lastName == null : this.lastName.equals(profile.lastName)) &&
        (this.email == null ? profile.email == null : this.email.equals(profile.email)) &&
        (this.twitterName == null ? profile.twitterName == null : this.twitterName.equals(profile.twitterName)) &&
        (this.linkedinName == null ? profile.linkedinName == null : this.linkedinName.equals(profile.linkedinName)) &&
        (this.facebookName == null ? profile.facebookName == null : this.facebookName.equals(profile.facebookName)) &&
        (this.picture == null ? profile.picture == null : this.picture.equals(profile.picture)) &&
        (this.stakeholderId == null ? profile.stakeholderId == null : this.stakeholderId.equals(profile.stakeholderId)) &&
        (this.active == null ? profile.active == null : this.active.equals(profile.active));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.twitterName == null ? 0: this.twitterName.hashCode());
    result = 31 * result + (this.linkedinName == null ? 0: this.linkedinName.hashCode());
    result = 31 * result + (this.facebookName == null ? 0: this.facebookName.hashCode());
    result = 31 * result + (this.picture == null ? 0: this.picture.hashCode());
    result = 31 * result + (this.stakeholderId == null ? 0: this.stakeholderId.hashCode());
    result = 31 * result + (this.active == null ? 0: this.active.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Profile {\n");
    
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  twitterName: ").append(twitterName).append("\n");
    sb.append("  linkedinName: ").append(linkedinName).append("\n");
    sb.append("  facebookName: ").append(facebookName).append("\n");
    sb.append("  picture: ").append(picture).append("\n");
    sb.append("  stakeholderId: ").append(stakeholderId).append("\n");
    sb.append("  active: ").append(active).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
